### ISSUE TITLE
Upgrade version  from 0.5.2 to 0.5.3. is not shown in the app:list output

### ISSUE THREAD

**Issue by davitol** [owncloud/twofactor_totp#106]
![screen shot 2019-03-08 at 10 04 28](https://user-images.githubusercontent.com/10596560/54019186-dcf75600-418a-11e9-9aad-3f97c033b7c6.png)

But the bits seems to have been updated

![screen shot 2019-03-08 at 10 14 18](https://user-images.githubusercontent.com/10596560/54019228-f7c9ca80-418a-11e9-8beb-01de0e015b72.png)

**Comment by PVince81** [comment]
sounds like https://github.com/owncloud/core/pull/34133

@davitol did you try running the command multiple times ?

the DB update for the version is only done on the next HTTP request and possibly OCC.
maybe `occ app:list` is fetching the list too early before said DB update...

please also check oc_appconfig values

**Comment by davitol** [comment]
> @davitol did you try running the command multiple times ?

Retested and works. So it was probably due to https://github.com/owncloud/core/pull/34133. Also checked in oc_appconfig and everything is OK. Let's close the ticket
