### ISSUE TITLE
[bug] App doesn't play nice with asset pipeline

### ISSUE THREAD

**Issue by rmbleeker** [owncloud/twofactor_totp#12]
**OwnCloud version:** 9.1.5.2
**OS version:** CentOS 7
**PHP version:** 7.0.10
**Two Factor TOTP version:** 0.4.2

I've been struggling with this issue for a while, trying to retrace my steps with all the security and performance tweaks I've applied to my OwnCloud installation. I won't bore you with the details, but I finally found out that the Two Factor TOTP Provider app doesn't work when you have `'asset-pipeline.enabled' => true,` set in your *config.php*. The proper section is added to the users' *Personal* menu, but instead of showing a tickbox to **Enable TOTP** there's a blank space. This means users who haven't enabled 2FA yet can't activate it, and users who have it enabled can't deactivate it.

**Comment by DeepDiver1975** [comment]
oc10 killed the asset pipline because of this any many other issues. Please update these days .... or test the release candidate now :wink: THX

**Comment by rmbleeker** [comment]
Since this is an OwnCloud server used in a business we will stick with the stable version for now, which seems to be the version I'm on currently. However it's good to know that the asset pipeline is indeed causing issues and will be removed in future versions.
