### ISSUE TITLE
Two Factor TOTP not compatible with OwnCloud 10

### ISSUE THREAD

**Issue by rmbleeker** [owncloud/twofactor_totp#14]
In issue #12 I was advised to upgrade to OwnCloud 10, so I did as soon as it became available in the stable channel (today). Unfortunately it seems the twofactor_totp app is not yet compatible with OwnCloud 10:

```
This app cannot be installed because the following dependencies are not fulfilled:

- ownCloud 9.1 or lower is required.

```

Hopefully this app can be updated soon so I can use it again.

**Comment by DeepDiver1975** [comment]
please grab an update of the app via the marketplace - https://marketplace.owncloud.com/apps/twofactor_totp

best is to use the occ command:

```sh
../occ market:upgrade twofactor_totp

**Comment by rmbleeker** [comment]
> best is to use the occ command:
> `../occ market:upgrade twofactor_totp`

This gives me 

> twofactor_totp: No update available

**Comment by DeepDiver1975** [comment]
the app version needs to be updated .... will take care ...

**Comment by DeepDiver1975** [comment]
fixed with https://github.com/owncloud/twofactor_totp/pull/17
