### ISSUE TITLE
App not allowed in Owncloud 10.0

### ISSUE THREAD

**Issue by Tekuzo** [owncloud/twofactor_totp#15]
After updating Owncloud to 10.0, owncloud refused to finish the update until this app was disabled. 

After disabling this app, owncloud successfully updated to 10.0 and inside of the app management screen this app has the error message beside it

"This app cannot be installed because the following dependencies are not fulfilled:
ownCloud 9.1 or lower is required."

**Comment by DeepDiver1975** [comment]
Update the app via the market app.
