### ISSUE TITLE
0.4.2 (OC 10) doesn't work with PHP 7.1

### ISSUE THREAD

**Issue by Wurmdosungen** [owncloud/twofactor_totp#16]
After upgrading to OC 10, two factor authorization with the OC 10 app "Two Factor TOTP Provider 0.4.2" stopped working, saying that the app requires a PHP version <= 7.0.

The good news might be that, for me, the code itself seems to work with PHP 7.1. So, a simple temporary workaround is to modify the file owncloud/apps/twofactor_totp/appinfo/info.xml, replacing the line

`<php min-version="5.4" max-version="7.0" />`

with

`<php min-version="5.4" max-version="7.1" />`

Of course this results in code signing warning messages, but for the time being, this is a lesser inconvenience than living without two-factor authorization.

Kind regards,
   Christian

**Comment by DeepDiver1975** [comment]
fixed with https://github.com/owncloud/twofactor_totp/pull/17
