### ISSUE TITLE
twofactor_totp 0.7.0

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/twofactor_totp#180]
### Reason

- Release needed for owncloud/twofactor_totp#175

### Product approval

- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [ ] Verify transifex commits are in master - last commit two months ago
- [x] Create release branch with the format "release-$version"

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Sanity tested with oC 10.5 and PHP 7.4.

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol RC1 https://github.com/owncloud/twofactor_totp/releases/tag/v0.7.0RC1

**Comment by davitol** [comment]
> @davitol RC1 https://github.com/owncloud/twofactor_totp/releases/tag/v0.7.0RC1

Tarball is QA-ready :shipit:

**Comment by jnweiger** [comment]
https://github.com/owncloud/twofactor_totp/releases/tag/v0.7.0 is public

**Comment by jnweiger** [comment]
min version remains at 10.2 -- its a community app, although it only is included in the specs of the owncloud-complete server bundle...
