### ISSUE TITLE
Bad TOTP setup workflow for users: lockout possible

### ISSUE THREAD

**Issue by Bebef** [owncloud/twofactor_totp#20]
TOTP 0.4.3
OC 10.0.0.12

If you go to security settings and enable TOTP, it will stay enabled regardless of a successful test. So if you enable TOTP and then just log out, you won't be able to recover your account.

Administrators can't disable TOTP for users. The only way to recover is to disable the TOTP app (trough an admin account).

**Comment by karakayasemi** [comment]
#1 also mentioning about the same problem. AFAIK backup codes will implement for belonging to this issue.

**Comment by Bebef** [comment]
@karakayasemi Backup codes might be used to mitigate the issue, but the activation of 2FA should not be broken regardless.

**Comment by rmbleeker** [comment]
As an Administrator you actually can disable 2FA on a per-user basis using the occ command. `occ twofactorauth:disable username` will disable 2FA for that user only. You can still toggle the tickbox in the GUI for that user, but it won't have any effect until the command `occ twofactorauth:enable username` is invoked.

**Comment by DeepDiver1975** [comment]
we have backup codes now as well as a verification workflow - see #27 

we can close this from my pov

**Comment by Bebef** [comment]
@DeepDiver1975 Has the setup process been changed in a way that allows you to enable two factor auth only after verifying it? Backup codes are nice, but also are just a workaround to this issue...

**Comment by karakayasemi** [comment]
Yes it was changed, see #28

**Comment by rmbleeker** [comment]
Does anyone know when this update will be pushed through the OwnCloud Marketplace? I'm still on version 0.4.3
