### ISSUE TITLE
Can't enable TOTP (no authentication code)

### ISSUE THREAD

**Issue by Gehilfe** [owncloud/twofactor_totp#202]
Hi,
after updating my owncloud to 10.5.0.10 I could not connect to my cloud with TOTP. I had to disable the app manually via terminal to log in again.

After restoring my mysql backup, I was able to log in to the owncloud again and also click the checkbox to activate the TOTP app. The QR code also appears but unfortunately no authentication code is displayed. I'm using PHP7.2 on Ubuntu Server 16.04.

Can you give me a tip?

**Comment by karakayasemi** [comment]
please check is there any related owncloud.log lines for your problem.

**Comment by Gehilfe** [comment]
Unfortunately, the log file does not provide any useful information about my problem

**Comment by Gehilfe** [comment]
ok, i'm totally stupid. Sorry! I just had to enter the code from the TOTP app. Everything is working fine now.
