### ISSUE TITLE
Can't enable TOTP for users (Internal 500 error)

### ISSUE THREAD

**Issue by bossman90** [owncloud/twofactor_totp#206]
ownCloud Version: 10.6.0
php Version: 7.4

Expected behavior…
Click your user name and then click “Security”. a check box is displayed under the TOTP Second-factor Auth section, click the check box and a QR code will show up where you can scan and enter the code provided by the app in order to authenticate.

Unexpected behavior…
Click your user name and then click “Security”. a check box is displayed under the “TOTP Second-factor Auth” section, click the check box nothing happens.

On clicking “Activate 2FA” in Users Settings, the server responds with an “500 Internal Server Error”

https://____/index.php/apps/twofactor_totp/settings/enable
Status500
Internal Server Error
VersionHTTP/2

owncloud.log

{"reqId":"znWyPGQmVIMV1y8x0v4X","level":3,"time":"2021-01-04T02:03:26+00:00","remoteAddr":"XXX","user":"XXX","app":"index","method":"POST","url":"\/index.php\/apps\/twofactor_totp\/settings\/enable","message":"Exception: {\"Exception\":\"BaconQrCode\\\\Exception\\\\RuntimeException\",\"Message\":\"You need to install the imagick extension to use this back end\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/twofactor_totp\\\/lib\\\/Controller\\\/SettingsController.php(138): BaconQrCode\\\\Renderer\\\\Image\\\\ImagickImageBackEnd->__construct()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/twofactor_totp\\\/lib\\\/Controller\\\/SettingsController.php(83): OCA\\\\TwoFactor_Totp\\\\Controller\\\\SettingsController->generateBase64EncodedQrImage()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\TwoFactor_Totp\\\\Controller\\\\SettingsController->enable()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(917): OC\\\\Route\\\\Router->match()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/twofactor_totp\\\/vendor\\\/bacon\\\/bacon-qr-code\\\/src\\\/Renderer\\\/Image\\\/ImagickImageBackEnd.php\",\"Line\":64}"}

**Comment by phil-davis** [comment]
https://doc.owncloud.com/server/admin_manual/installation/quick_guides/ubuntu_18_04.html#install-the-required-packages

`php-imagick` is one of the required extensions. So make sure to install that, and all the needed extensions. For example, on Ubuntu:
```
sudo apt install php-imagick
```
