### ISSUE TITLE
Cloud ID generation bug

### ISSUE THREAD

**Issue by iben12** [owncloud/twofactor_totp#22]
When owncloud is installed in a subdirectory (ie. mydomain.com/owncloud), the generated cloud ID is displayed as `user@mydomain.com/owncloud`. The barcode is generated with this ID and becomes invalid.

Using manual entry with `user@mydomain.com` works, just not very convenient.

**Comment by DeepDiver1975** [comment]
This should not work with the latest code base

**Comment by karakayasemi** [comment]
I installed owncloud to mydomain.com/core. Cloud ID is generated as user@mydomain.com/core and Totp is working. Using Manual entry with user@mydomain.com works also. Am I misunderstanding your problem? Can you please give explicit steps. Thanks

**Comment by iben12** [comment]
When I try to scan the generated barcode with Google Authenticator on iOS, I get an
```
Invalid barcode
... is not a valid authentication token barcode.
```
error. See screenshot at http://imgur.com/a/v4vy1

However entering the user and secret manually just works.

**Comment by DeepDiver1975** [comment]
the value of issuer is a url - according to the code it should be 'ownCloud' (assuming you are not using a theme)

which version of this app are you using?

**Comment by iben12** [comment]
I am using ownCloud 9.1.6 and TOPT 0.4.2

There are two issues here that I can see:

- ownCloud generates the Cloud ID including not only the TLD, but additional URL path (like `user@mydomain.com/owncloudsubfolder`). This is valid just
 does not work when entered into Google Authenticator (see in workaround).

- The TOPT app generates the barcode using the above Cloud ID and the issuer like `https://mydomain.com/owncloudpath (ownCloud)` which I guess should be a valid URL, but it is not. Because of this, scanning the barcode with Google Authenticator throws an `Invalid barcode` error, so it can't be used to easily add the service.

The current workaround for me was to enter the Cloud ID omitting the subfolder path and the secret into Google Authenticator manually. Also tried to enter the Cloud ID including the whole URL path, in which case Authenticator accepts it and everything seems OK, but you just can't authenticate with the generated token when trying to sign in to ownCloud.

**Comment by karakayasemi** [comment]
A bug have fixed in upstream repository which may cause to this issue if url has special characters: https://github.com/ChristianRiesen/otp/pull/29

We will update the related dependency with this PR and I am planning to close this issue after merging the update PR. If error still persist, please re-open the issue. Thanks.
