### ISSUE TITLE
TOTP cannot be re-enabled

### ISSUE THREAD

**Issue by BentiGorlich** [owncloud/twofactor_totp#224]
Hello,

I disabled totp for my owncloud account because I didn't have the qr code anymore and only had it on my tablet, but not on my phone. If I want to re-enable it, a qr code does not show up and the request returns a 500 internal server error. So I can't re-enable it on my server.

I don't know if it is a error specificaly on my owncloud instance or if it is a bug, but I hope you can eigher help me fix my problem or solve this bug if it is one.

**Comment by realUbie** [comment]
Can confirm, nothing happens when you tick the "Activate TOTP" checkbox

**Comment by realUbie** [comment]
I couldn't find any helpful logs, ended up reinstalling my ownCloud instance, which solved this issue

**Comment by dillon-sykes** [comment]
I've just had the same issue with the "2-Factor Authentication" app in the marketplace.

For anyone having this issue in the future, the php-imagick PHP extension needs to be installed. I found this was missing from the ownCloud server which this app relies on. After installing this PHP extension and restarting apache, QR codes are now displayed and there are no errors in the console.

**Comment by dillon-sykes** [comment]
For anyone having this issue, the php-imagick PHP extension needs to be installed. I found this was missing from the ownCloud server, the "2-Factor Authentication" app in the marketplace relies on this extension to work correctly. After installing this PHP extension and restarting apache, QR codes are now displayed and there are no errors in the console.
