### ISSUE TITLE
App Passwords get lost

### ISSUE THREAD

**Issue by treuss** [owncloud/twofactor_totp#23]
**OwnCloud version: 10.0.0
OS version: Raspbian 8 (Jessie)
PHP version: 5.6.30
Two Factor TOTP version: 0.4.3**

After having set up some app passwords (it was about 6-8 of them), twofactor_totp loses a random one of them. When I re-add it, another random password gets lost. 

This issue doesn't appear, if I only use one app password.

**Comment by DeepDiver1975** [comment]
I cannot reproduce this - can you please give explicit steps? THX

**Comment by treuss** [comment]
Hi @DeepDiver1975 ,

sorry for the late response - I've been on vacation during the last weeks.

I just set up two extra app passwords next to the functional one I've been using during the past months.
The steps were the exact same ones I did before:
1. Go to personal settings --> App-Passwords
2. Enter a name: "[DEVICE NAME] Sync"
3. Click on create new app password
4. Store the new password in my password safe
5. Click on finish
Like before, the newly created passwords are showing up. I'll test now if they keep on working or if they again disappear as they did when I filed this issue,

Thanks for your efforts
Thomas

**Comment by DeepDiver1975** [comment]
@karakayasemi wana have a look? THX

**Comment by karakayasemi** [comment]
Firstly, IMHO it can not be related to twofactor_totp app. App passwords are stored in authtoken table in database. Totp never touches to auth-tokens. Auth-tokens are implemented in core. Anyway, I also tested given steps. 
1-) I created 6 new app password.
2-) Enabled totp
3-) I tried to login with tokens.
All of them worked. @treuss  am I missing something?

**Comment by treuss** [comment]
Hi @karakayasemi ,

thank you for clarifying the internals - I didn't even know, that these tokes were a core feature. 

I've no idea what happened back then when I reported this bug. Maybe some weird caching problems. However, I've been testing with 3 App Passwords during the last days and it seems to work now. No more disabled App Passwords.

Sorry for the inconvenience and thanks again!

**Comment by karakayasemi** [comment]
@treuss Thank you for reporting effort at least :) If it happens again, the correct address is core repo. You can open an issue in core.
