### ISSUE TITLE
Minimum version of ownCloud required

### ISSUE THREAD

**Issue by andyforceno** [owncloud/twofactor_totp#24]
Is this compatible with ownCloud 9? I was unable to install the latest version, but I could install 0.4.1 and then upgrade within ownCloud to 0.4.2. Except, there are no app options in the admin settings for ownCloud. I'm guessing this requires ownCloud 10 now? The listing on apps.owncloud.com implies it should work with 9 (but the newer marketplace page is pretty clear that it's for 10 only). 

I can't seem to find a working implementation of 2FA for ownCloud 9, and yet ownCloud themselves claim it is possible. Privacyidea didn't work, either. I'm getting the feeling I should have installed NextCloud instead.

**Comment by DeepDiver1975** [comment]
9.1 is the least minimal version - 9.1 allows two factor auth in the server.
just open up your apps mgmt page in 9.1 and install it - the version on https://apps.owncloud.com/content/show.php/TOTP+TwoFactor+%28Google+Authenticator%29?content=174726 is ready for 9.1
