### ISSUE TITLE
No app settings on admin page

### ISSUE THREAD

**Issue by andyforceno** [owncloud/twofactor_totp#25]
I installed v0.4.2 from apps.owncloud.com, but there are no options for it in the admin page. I see in the one screenshot there should be a section "TOTP Second-Factor Auth" in the settings, but I don't have that in mine. There are no errors in ownCloud since I installed the app. Any ideas?

**Comment by DeepDiver1975** [comment]
please have a look in the personal settings. there are no admin settings.
