### ISSUE TITLE
Two Factor TOTP Provider 0.4.3 for Owncloud 10.0, never success verify

### ISSUE THREAD

**Issue by pfuentes1402** [owncloud/twofactor_totp#26]
I am using Two Factor TOTP Provider 0.4.3 for Owncloud 10.0, i could installed and configure but never verify success. To generating codes I am using some application like Google Authenticator, FreeOTP and OTP Authenticator.
When I get the code from the secret token and try to verify it, it says "Not verify"
How i can resolve this problem?

**Comment by karakayasemi** [comment]
Could it be because of the difference in timezone? Please check if your phone and server clocks are out of sync.

**Comment by pfuentes1402** [comment]
thanks you, working success to try after syncronice server and phone.

**Comment by karakayasemi** [comment]
Good to hear that. Can we close this issue then?
