### ISSUE TITLE
[QA] missing dependency on php-imagick

### ISSUE THREAD

**Issue by jnweiger** [owncloud/twofactor_totp#260]
Seen with twofactor_totp 0.7.4 and core 10.9.1 on Ubuntu 20.04 where php-imagick is not installed.

* admin enables the twofactor_totp app
* admin navigates to his personal settings -> security and clicks the TOTP checkbox
![image](https://user-images.githubusercontent.com/1108546/154510098-c6d34c55-11c8-4e92-a7f3-ba8703615962.png)
----
* no QR code is rendered. No error messages are shown. BAD.
* The server log has an error:
```
{"reqId":"Yg5j-kuXTDg1DUWH4sIamwAAAAg","level":3,"time":"2022-02-17T15:04:30+00:00","remoteAddr":"2.247.252.56","user":"admin","app":"index","method":"POST","url":"\/index.php\/apps\/twofactor_
totp\/settings\/enable","message":"Exception: {\"Exception\":\"BaconQrCode\\\\Exception\\\\RuntimeException\",\"Message\":\"You need to install the imagick extension to use this back end\",\"Co
de\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/twofactor_totp\\\/lib\\\/Controller\\\/SettingsController.php(138): BaconQrCode\\\\Renderer\\\\Image\\\\ImagickImageBackEnd-
>__construct()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps-external\\\/twofactor_totp\\\/lib\\\/Controller\\\/SettingsController.php(83): OCA\\\\TwoFactor_Totp\\\\Controller\\\\SettingsController->
generateBase64EncodedQrImage()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(170): OCA\\\\TwoFactor_Totp\\\\Controller\\\\SettingsController->enabl
e()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#4 \\\/var\\\/www\\\/ownclou
d\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteAc
tionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invo
ke()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(927): OC\\\\Route\\\\Router->match()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/v
ar\\\/www\\\/owncloud\\\/apps-external\\\/twofactor_totp\\\/vendor\\\/bacon\\\/bacon-qr-code\\\/src\\\/Renderer\\\/Image\\\/ImagickImageBackEnd.php\",\"Line\":64}"}
{"reqId":"Yg5kDGOH7C1kRGxaEmLZRAAAAAI","level":0,"time":"2022-02-17T15:04:45+00:00","remoteAddr":"2.247.252.56","user":"admin","app":"OC\\User\\Session::validateToken","method":"POST","url":"\/
index.php\/apps\/twofactor_totp\/settings\/enable","message":"token 58c571734257c25382de8f3241ecaf4ea00c7200c7b6df86a7395f1482d63f02682c98bde0800f95cf816a563e62ab0a0acbd957b3874a62a694de96fc97a
dee with token id 1 found, validating"}
```

Expected behaviour:
* The app cannot be enabled, when dependencies are missing, or
* An error message mentioning the PHP module imagick is shown to the user, when wants to activate TOTP.

Manual workaround on Ubuntu:

`apt install php-imagick; service apache2 restart`

**Comment by phil-davis** [comment]
@jnweiger when I enable the app from the webUI admin settings it does a call to https://github.com/owncloud/core/blob/master/settings/ajax/enableapp.php

That code calls `OC_App::enable` in the same way that the occ command calls `OC_App::enable` - and both should call `checkAppDependencies` with the same parameters. So I don't immediately see how there can be a difference.

On my local system I get:
```
$ php occ a:e twofactor_totp

In app.php line 1129:
                                                                                                                                                 
  App "2-Factor Authentication" cannot be installed because the following dependencies are not fulfilled: The library imagick is not available.  
                                                                                                                                                 

app:enable [-g|--groups GROUPS] [--] <app-id>
```

And:
![Screenshot 2022-04-06 at 20-01-11 Settings - ownCloud](https://user-images.githubusercontent.com/1535615/161995874-7c54e1b0-2d47-4bf2-85b1-0479b07ef6fb.png)

So the app cannot be enabled via either method.

**Comment by ilgio** [comment]
I have same problem
how do I resolve?
I updated owncloud to 10.11 but doesent work

**Comment by jnweiger** [comment]
@ilgio did you try the mentioned
Manual workaround on Ubuntu:

`apt install php-imagick; service apache2 restart`

**Comment by voroyam** [comment]
Seen in oC 10.12.1. I installed the app via market app in the WebUI - no dependency warning. Why is the fix of this issue not in the release of the latest release?

**Comment by jnweiger** [comment]
This is unrelated to 10.12.1 - twofactor_totp is not in the minimal and not in the complete bundle.
