### ISSUE TITLE
Make a verification of the second factor mandatory after enabling TOTP

### ISSUE THREAD

**Issue by Helios07** [owncloud/twofactor_totp#27]
Is there a chance to make it mandatory for the user to verify the second factor before enabling the app?

I have the strong feeling that many users won't really understand what the app does and enable it accidentally. It will become a problem for us, even if the probability is low, because we have almost 100k users...

Thank you very much!

**Comment by karakayasemi** [comment]
We can add this feature if everyone agrees, also we can add password confirmation before enabling.

**Comment by Helios07** [comment]
Any news on this? Is there anything I can do to help?

**Comment by karakayasemi** [comment]
I don't think anyone would object, no need to wait. Probably, this weekend I will implement it.

**Comment by karakayasemi** [comment]
Please test #28.
