### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Touchwoody** [owncloud/twofactor_totp#29]
Does this app provide a REST API similar to OTP servers? Something like
https://host/path/validate/check?user=username&pass=123456 to validate an OTP key?

So long,

**Comment by karakayasemi** [comment]
Unfortunately, does not provide a REST API, but IMHO not hard to implement.

**Comment by Touchwoody** [comment]
If you consider it doable, it'll be a great help.
We have a bunch of user management websites/-scripts alongside our owncloud installation (sciebo), where some authorized users can do administrative stuff. I'd very much like to safeguard these actions a little bit better and a twofactor mechanism that is already tied to the present user accounts would be a great choice.

**Comment by karakayasemi** [comment]
I will implement when I find time.

**Comment by karakayasemi** [comment]
resolved wıth #38 . It will be in 0.6.0.
