### ISSUE TITLE
0.4.4 Release plan

### ISSUE THREAD

**Issue by pmaier1** [owncloud/twofactor_totp#31]
**Reason**
- Release needed for https://github.com/owncloud/twofactor_totp/issues/27

**QA**
- [x] Create release branch -  release/0.4.4
- [x] Create "$version Testplan" - https://github.com/owncloud/twofactor_totp/issues/40
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

**Marketing**
- [x] Check/adapt info.xml stuff @pmaier1 https://github.com/owncloud/twofactor_totp/pull/45
- [ ] ~~Check/adapt screenshot~~ => not applicable
- [ ] ~~Blog post or other communication if applicable~~ => not applicable

**Documentation**
- [ ] ~~Changes in the docs needed?~~ => not applicable

**Build & Marketplace release**

- [x] Bump version in info.xml -> #28 
- [x] Update CHANGELOG.md
- [x] Create github tag for '$version'
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [ ] Send mail to release-coordination with link to this ticket and changelog
- [x] Rename QA milestone to '$version'
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] Create PR to merge changes back to `master`

**Comment by patrickjahns** [comment]
@pmaier1 
Can not be released - appinfo.xml is still missing a summary

**Comment by pmaier1** [comment]
Info.xml PR https://github.com/owncloud/twofactor_totp/pull/45
