### ISSUE TITLE
Second factor verification page mentions google authenticator

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/twofactor_totp#41]
![screen shot 2018-01-15 at 13 01 20](https://user-images.githubusercontent.com/9048796/34942230-20d18bf2-f9f7-11e7-8895-4c72f4cab695.png)

There is no need to use Google Authenticator with this app, there are other apps. For example FreeOTP.

What do you think @pmaier1

**Comment by pmaier1** [comment]
Good point. For the sake of clarity we should have a more general wording here :+1: Either there is a more general name for services like Google Authenticator or we could remove it and instead just say "Time-based one-time password"

**Comment by SergioBertolinSG** [comment]
It this a blocker for 0.4.4 release?

**Comment by pmaier1** [comment]
> It this a blocker for 0.4.4 release?

No. But should be easy to change that text, right?

**Comment by SergioBertolinSG** [comment]
Yes, I've made the PR:

https://github.com/owncloud/twofactor_totp/pull/43

**Comment by pmaier1** [comment]
Thanks! It's merged.
