### ISSUE TITLE
OTP disables syncing CALDAV/CARDDAV/WEBDAV

### ISSUE THREAD

**Issue by rene1970** [owncloud/twofactor_totp#50]
After installing OTP i noticed that syncing through the remote.php doesnt work anymore. That's very unconvenient. Is there a workaround or solution for this issue? Any help would be appreciated.

**Comment by karakayasemi** [comment]
Enabling a second factor will automatically enforce token-based authentication for clients. Please use app password for client authentication. You can app password in your personal settings page. You can open this issue if your problems continue.

**Comment by rene1970** [comment]
Your going a bit to fast here mate. What are you trying to say? That i should not use 2FA if i want to use clients? What do you exactly mean with "Please use app password for client authentication. You can app password in your personal settings page."?

**Comment by phil-davis** [comment]
Login to the webUI, go to the Settings, Personal, Security page. Add an App Password. Put that app password into the client instead of the regular password.

**Comment by bitterdev** [comment]
hello i have owncloud. Since i'm using 2FA webdav is not working anymore. Even if i use app Passwords.
