### ISSUE TITLE
0.5.0 Testplan

### ISSUE THREAD

**Issue by individual-it** [owncloud/twofactor_totp#58]
All tests run with TOTP [0.5.0](https://github.com/owncloud/twofactor_totp/tree/release-0.5.0) & ownCloud 10.0.10RC2

## Twofactor TOTP Test Plan

| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| Enable the app.                          | No problems found.                       | ✅  |                 |
| Using a non admin user user1, enable totp in the personal settings.<br />Having the app freeotp (android or ios) scan the QR code provided - enter a random verification code | code is not verified |  ✅            |                 |
| Using a non admin user user1, enable totp in the personal settings.<br />Having the app freeotp (android or ios) scan the QR code provided and set it up.<br />Login using user1, get a new code in the freeotp app. Introduce it in the login view. Login. | User1 can login without problems.        | ✅            |                 |
| Using a non admin user user1, enable totp in the personal settings.<br />Having the app freeotp (android or ios) scan the QR code provided and set it up.<br />Login using user1, get a new code in the freeotp app. Introduce it in the login view. Login. Logout. Login again using same code | User1 cannot login without a new code        | :x:             |          #59       |
| Using users user1 & user2, enable totp and set it up in the personal settings.<br />Login using user1, get a new code in the freeotp app for user2. Introduce it in the login view. Login. | user1 cannot login      | ✅            |                 |
| Using users user1, enable totp and set it up in the personal settings.<br />Login using user1, totp.<br />Disable TOTP in the personal settings of user1. Login again | user1 can login without TOTP token      | ✅            |                 |
| Using users user1, enable totp and set it up in the personal settings.<br />Login using user1, totp.<br />Disable TOTP in the personal settings of user1<br/> Enable it again, set it up scanning the new QR code. | new verification code is accepted      | ✅            |                 |
| Using users user1, enable totp and set it up in the personal settings.<br />Login using user1, totp.<br />Disable TOTP in the personal settings of user1<br/> Enable it again, do **not** scan the new QR code but use a current code from the first setup to verify | code is not accepted      | ✅            |                 |
| Using a non admin user user1, enable totp in the personal settings.<br />Having the app freeotp (android or ios) scan the QR code provided and set it up.<br />Try to login with user1 using his password. When the totp input appears introduce random numbers, emojis, negative numbers and empty string. | User1 cannot login in any of this situations. | ✅              |                 |
| Using a LDAP user ldap_user, enable totp in the personal settings.<br />Having the app freeotp (android or ios) scan the QR code provided and set it up.<br />Login using ldap_user, get a new code in the freeotp app. Introduce it in the login view. Login. | User_ldap can login without problems.    | ✅              |                 |
| Using a non admin user user1, enable totp in the personal settings.<br />Having the app **google authenticator** (android or ios) scan the QR code provided and set it up.<br />Login using user1, get a new code in the **google authenticator** app. Introduce it in the login view. Login. | User1 can login without problems.        | ✅             |                 |
| Using a non admin user user1, enable totp in the personal settings.<br />Having the app **google authenticator** (android or ios) set up the account in the app using the key.<br />Login using user1, get a new code in the **google authenticator** app. Introduce it in the login view. Login. | User1 can login without problems.        | ✅             |                 |
| **CLI**                             |                                          |                |                 |
| Test 1/2 Having a user 'user1' with a working enabled two factor authentication, use the CLI command to disable it twofactorauth:disable                           |   'user1' now can login without using 2FA                                       |  ✅               |                 |
| Test 2/2 Use the CLI command twofactorauth:enable to enable again 2FA for 'user1'   |   'user1' has to use 2FA mandatory to login                                       |  ✅               |                 |
| **Browsers**                             |                                          |                |                 |
| Check the login process is possible using chrome |                                          | ✅             |                 |
| Check the login process is possible using firefox |                                          | ✅              |                 |
| Check the login process is possible using edge |                                          | ✅             | <br />          |
| Check the login process is possible using internet explorer 11 |                                          | ✅             | <br />          |
| Check the login process is possible using safari |                                          | ✅             |                 |

**Comment by karakayasemi** [comment]
@PVince81 Shall we close?
