### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Artemiis** [owncloud/twofactor_totp#6]
I don't get it working.

I installed from owncloud app store and i'he cloned this repo (with make after that), i can enable two-factor and scan the wr code with otp or google but the code doesn't unlock my owncloud.
Are there any logs, the codes are equal, so they are right.
I#M running lates Owncloud 9.1.4 stable

**Comment by DeepDiver1975** [comment]
> scan the wr code with otp or google but the code doesn't unlock my owncloud.

is the clock of your mobil in sync? is the clock of your servce in sync?

if not - the one time pass can not be validated

**Comment by mundschenk-at** [comment]
Same problem here, clocks should be in sync (NTP on server/network on phone).

**Comment by Artemiis** [comment]
Sorry,  i retested, my server clock was 2mins to fast. Thanks for tip!
