### ISSUE TITLE
php-cs-fixer 

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/twofactor_totp#62]
The code does not follow ownCloud code style. We should introduce php-cs-fixer.

**Comment by patrickjahns** [comment]
Makefile and `.drone.yml` from https://github.com/owncloud/password_policy are a good starting point.

I am proposing to use `composer-bin` in order to separate dependencies from cli tools ( such as cs-fixer / phan / stan ) from dependencies of the project itself.

**Comment by karakayasemi** [comment]
I guess, it is resolved with #77.
