### ISSUE TITLE
0.4.2 doesn't include fixes in 0.4.1

### ISSUE THREAD

**Issue by scolebrook** [owncloud/twofactor_totp#7]
It seems that the commit tagged as 0.4.1 is not an ancestor of the later commits for 0.4.2 and branches stable9.1 and master. The split is at the tag 0.4 (2ed3b44) so there's a bunch of fixes in 0.4.1 that aren't in 0.4.2. Not sure the best way to resolve this or where to create a new branch from for a new feature.

**Comment by DeepDiver1975** [comment]
very much true - damn spoooning .... I'll add these commits to master and stable9.1.
